import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@gateflow/ui';
import { Button, Checkbox, Label } from '@gateflow/ui';
import { AlertTriangle } from 'lucide-react';

interface PublishDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => void;
  aiGeneratedCount: number;
}

export function PublishDialog({
  isOpen,
  onClose,
  onConfirm,
  aiGeneratedCount,
}: PublishDialogProps) {
  const [checks, setChecks] = useState({
    content: false,
    images: false,
    links: false,
  });

  const allChecked = checks.content && checks.images && checks.links;

  return (
    <Dialog open={isOpen} onOpenChange={(open: boolean) => !open && onClose()}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Publish Landing Page</DialogTitle>
          <DialogDescription>
            You are about to publish a page with {aiGeneratedCount} AI-generated
            sections.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {aiGeneratedCount > 0 && (
            <div className="bg-ds-background-warning-subtle border border-ds-border-warning p-4 rounded-md flex gap-3">
              <AlertTriangle className="h-5 w-5 text-ds-text-warning shrink-0 mt-0.5" />
              <div>
                <h4 className="font-semibold text-ds-text-warning text-sm">
                  AI Content Detected
                </h4>
                <p className="text-sm text-ds-text-warning/90 mt-1">
                  This page contains {aiGeneratedCount} sections generated by
                  AI. Please review all content before publishing.
                </p>
              </div>
            </div>
          )}

          <div className="space-y-3">
            <Label className="font-semibold">Review Checklist</Label>
            <div className="space-y-3">
              <div className="flex items-start gap-2">
                <input
                  type="checkbox"
                  id="review-content"
                  checked={checks.content}
                  onChange={(e) =>
                    setChecks((s) => ({ ...s, content: e.target.checked }))
                  }
                  className="peer h-4 w-4 shrink-0 rounded-sm border border-ds-border ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                />
                <Label
                  htmlFor="review-content"
                  className="leading-tight cursor-pointer"
                >
                  I have reviewed all text content
                </Label>
              </div>
              <div className="flex items-start gap-2">
                <input
                  type="checkbox"
                  id="review-images"
                  checked={checks.images}
                  onChange={(e) =>
                    setChecks((s) => ({ ...s, images: e.target.checked }))
                  }
                  className="peer h-4 w-4 shrink-0 rounded-sm border border-ds-border ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                />
                <Label
                  htmlFor="review-images"
                  className="leading-tight cursor-pointer"
                >
                  I have reviewed all images
                </Label>
              </div>
              <div className="flex items-start gap-2">
                <input
                  type="checkbox"
                  id="review-links"
                  checked={checks.links}
                  onChange={(e) =>
                    setChecks((s) => ({ ...s, links: e.target.checked }))
                  }
                  className="peer h-4 w-4 shrink-0 rounded-sm border border-ds-border ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                />
                <Label
                  htmlFor="review-links"
                  className="leading-tight cursor-pointer"
                >
                  I have verified all links work
                </Label>
              </div>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button
            onClick={onConfirm}
            disabled={aiGeneratedCount > 0 && !allChecked}
            className="bg-ds-background-brand-bold text-ds-text-inverse hover:bg-ds-background-brand-bold/90"
          >
            Confirm Publish
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
