import type { Metadata } from 'next';
import Link from 'next/link';
import {
  Zap,
  WifiOff,
  BarChart3,
  Shield,
  QrCode,
  Users,
  Clock,
  Globe,
  Webhook,
  KeyRound,
  Download,
  Bell,
} from 'lucide-react';

export const metadata: Metadata = {
  title: 'Features',
  description:
    'Explore every GateFlow feature: offline QR scanning, real-time analytics, multi-gate management, role-based access control, webhooks, API keys, and more.',
};

// ─── Data ──────────────────────────────────────────────────────────────────────

const FEATURES = [
  {
    icon: QrCode,
    title: 'HMAC-SHA256 Signed QR Codes',
    desc: 'Every QR code generated by GateFlow carries a cryptographic signature. Fakes, screenshots, and reprints are rejected in under 2 seconds — even without internet.',
    badge: 'Core',
  },
  {
    icon: WifiOff,
    title: 'Offline-First Scanning',
    desc: "The scanner app works 100% without WiFi. Scans are queued locally with AES-256 encryption and automatically synced when connectivity returns. scanUuid deduplication prevents double-counting.",
    badge: 'Core',
  },
  {
    icon: BarChart3,
    title: 'Advanced Analytics Dashboard',
    desc: 'Line charts, gate success rates, QR type breakdowns, peak hours heatmap, role distributions, and KPI trend indicators — all filterable by date range and project.',
    badge: 'Analytics',
  },
  {
    icon: Shield,
    title: 'Role-Based Access Control',
    desc: 'Five roles: ADMIN, TENANT_ADMIN, TENANT_USER, VISITOR, and RESIDENT (Phase 2). Every API route enforces org-scoped authorization. No cross-tenant data leakage.',
    badge: 'Security',
  },
  {
    icon: Users,
    title: 'Multi-Project Support',
    desc: 'Organize gates and QR codes into projects. Each project is a separate access namespace. Switch projects with a single click. Reports scope automatically.',
    badge: 'Organization',
  },
  {
    icon: Globe,
    title: 'Multi-Gate Management',
    desc: 'Create unlimited gates (Pro/Enterprise), assign them to projects, and see per-gate scan counts, success rates, and last access times in one view.',
    badge: 'Core',
  },
  {
    icon: Clock,
    title: 'Flexible QR Types',
    desc: 'SINGLE-use (expire after one scan), RECURRING (valid on schedule), or PERMANENT (always valid). Each type has configurable max-uses, expiry dates, and gate scope.',
    badge: 'Core',
  },
  {
    icon: Zap,
    title: 'Bulk CSV QR Creation',
    desc: 'Upload a CSV of visitor names and emails. GateFlow generates and emails signed QR codes to every recipient in seconds. Ideal for events with hundreds of attendees.',
    badge: 'Productivity',
  },
  {
    icon: Webhook,
    title: 'Webhooks & Event Delivery',
    desc: 'Subscribe to scan events, QR activations, and access denials. Each delivery attempt is logged with status code, response body, and retry history.',
    badge: 'Integration',
  },
  {
    icon: KeyRound,
    title: 'API Keys with Scopes',
    desc: 'Generate scoped API keys for programmatic access. Keys are stored as SHA-256 hashes — the plaintext is only shown once at creation.',
    badge: 'Integration',
  },
  {
    icon: Download,
    title: 'Scan Log Export',
    desc: 'Export any date range of scan logs to CSV, filtered by project, gate, status, or QR type. Includes project column and short ID suffix in filename.',
    badge: 'Compliance',
  },
  {
    icon: Bell,
    title: 'Supervisor Override Audit',
    desc: 'Supervisors can force-grant access to rejected scans using a PIN. Every override is logged server-side to the scan\'s audit trail with operator identity and reason.',
    badge: 'Compliance',
  },
];

const BADGE_COLORS: Record<string, string> = {
  Core: 'bg-indigo-50 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-400',
  Security: 'bg-red-50 dark:bg-red-950 text-red-700 dark:text-red-400',
  Analytics: 'bg-purple-50 dark:bg-purple-950 text-purple-700 dark:text-purple-400',
  Organization: 'bg-teal-50 dark:bg-teal-950 text-teal-700 dark:text-teal-400',
  Productivity: 'bg-orange-50 dark:bg-orange-950 text-orange-700 dark:text-orange-400',
  Integration: 'bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-400',
  Compliance: 'bg-green-50 dark:bg-green-950 text-green-700 dark:text-green-400',
};

const COMPARISON = [
  { feature: 'Real-time scan logs', traditional: false, gateflow: true },
  { feature: 'Offline verification', traditional: false, gateflow: true },
  { feature: 'Cryptographic QR signing', traditional: false, gateflow: true },
  { feature: 'Multi-gate management', traditional: false, gateflow: true },
  { feature: 'Bulk QR generation', traditional: false, gateflow: true },
  { feature: 'CSV export & audit logs', traditional: false, gateflow: true },
  { feature: 'Mobile scanner app', traditional: false, gateflow: true },
  { feature: 'Supervisor override audit', traditional: false, gateflow: true },
  { feature: 'API & webhook integration', traditional: false, gateflow: true },
  { feature: 'Paper guest book', traditional: true, gateflow: false },
  { feature: 'WhatsApp QR sharing (insecure)', traditional: true, gateflow: false },
  { feature: 'Manual log reconciliation', traditional: true, gateflow: false },
];

// ─── Page ──────────────────────────────────────────────────────────────────────

export default function FeaturesPage() {
  return (
    <main>
      {/* Hero */}
      <section className="relative overflow-hidden px-6 pb-16 pt-24 sm:pt-32">
        <div
          className="absolute inset-x-0 -top-40 -z-10 overflow-hidden blur-3xl"
          aria-hidden="true"
        >
          <div className="relative left-1/2 w-[64rem] -translate-x-1/2 bg-gradient-to-r from-indigo-600/20 to-[#00C9A7]/20 opacity-50" style={{ height: 600, borderRadius: '50%' }} />
        </div>
        <div className="mx-auto max-w-3xl text-center">
          <p className="mb-4 text-sm font-bold uppercase tracking-widest text-indigo-600">
            PLATFORM FEATURES
          </p>
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-6xl">
            Everything you need to run a secure gate
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-500 dark:text-slate-400">
            From cryptographic QR signing to offline scanning, advanced analytics, and full audit
            trails — GateFlow is built for serious access control.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/contact"
              className="rounded-xl bg-indigo-700 px-8 py-4 text-base font-bold text-white shadow-xl shadow-indigo-600/30 transition-all hover:-translate-y-0.5 hover:bg-indigo-600"
            >
              Start Free Trial
            </Link>
            <Link
              href="/pricing"
              className="rounded-xl border border-slate-200 dark:border-slate-700 px-8 py-4 text-base font-bold text-slate-700 dark:text-slate-200 transition-colors hover:bg-slate-50 dark:hover:bg-slate-800"
            >
              View Pricing
            </Link>
          </div>
        </div>
      </section>

      {/* Feature grid */}
      <section className="px-6 py-24">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((f) => {
              const Icon = f.icon;
              return (
                <div
                  key={f.title}
                  className="group rounded-2xl border border-slate-100 dark:border-slate-700 bg-white dark:bg-slate-800 p-7 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-xl"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400">
                      <Icon size={22} />
                    </div>
                    <span
                      className={`rounded-full px-2.5 py-0.5 text-xs font-bold ${BADGE_COLORS[f.badge] ?? 'bg-slate-100 text-slate-600'}`}
                    >
                      {f.badge}
                    </span>
                  </div>
                  <h3 className="text-base font-bold text-slate-900 dark:text-white">{f.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-slate-500 dark:text-slate-400">
                    {f.desc}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Comparison table */}
      <section className="bg-slate-50/50 dark:bg-slate-900/50 px-6 py-24">
        <div className="mx-auto max-w-4xl">
          <div className="mb-12 text-center">
            <p className="mb-3 text-sm font-bold uppercase tracking-widest text-indigo-600">
              COMPARISON
            </p>
            <h2 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white">
              GateFlow vs. Traditional Methods
            </h2>
          </div>
          <div className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-100 dark:border-slate-700">
                  <th className="p-4 text-left font-bold text-slate-900 dark:text-white">Feature</th>
                  <th className="p-4 text-center font-bold text-slate-500 dark:text-slate-400">
                    Traditional
                  </th>
                  <th className="p-4 text-center font-bold text-indigo-700 dark:text-indigo-400">
                    GateFlow
                  </th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON.map((row, i) => (
                  <tr
                    key={row.feature}
                    className={`border-b border-slate-50 dark:border-slate-700/50 last:border-0 ${
                      i % 2 === 0 ? '' : 'bg-slate-50/50 dark:bg-slate-800/50'
                    }`}
                  >
                    <td className="p-4 text-slate-700 dark:text-slate-200">{row.feature}</td>
                    <td className="p-4 text-center">
                      {row.traditional ? (
                        <span className="text-lg">✅</span>
                      ) : (
                        <span className="text-lg">❌</span>
                      )}
                    </td>
                    <td className="p-4 text-center">
                      {row.gateflow ? (
                        <span className="text-lg">✅</span>
                      ) : (
                        <span className="text-lg">❌</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-24">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white">
            Ready to see it in action?
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-lg text-slate-500 dark:text-slate-400">
            Book a 30-minute demo and we'll walk through your specific facility setup.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/contact"
              className="rounded-xl bg-indigo-700 px-8 py-4 text-base font-bold text-white shadow-xl shadow-indigo-600/30 transition-all hover:-translate-y-0.5 hover:bg-indigo-600"
            >
              Book a Demo
            </Link>
            <Link
              href="/pricing"
              className="rounded-xl border border-slate-200 dark:border-slate-700 px-8 py-4 text-base font-bold text-slate-700 dark:text-slate-200 transition-colors hover:bg-slate-50 dark:hover:bg-slate-800"
            >
              See Pricing
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
