import type { Organization, User } from './base';
export * from './base';

export interface UserWithOrganization extends User {
  organization?: Organization | null;
}

export const BUILT_IN_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  SECURITY_MANAGER: 'SECURITY_MANAGER',
  GATE_OPERATOR: 'GATE_OPERATOR',
  RESIDENT: 'RESIDENT',
} as const;

export const DEFAULT_PERMISSIONS: Record<
  string,
  Record<import('./base').Permission, boolean>
> = {
  [BUILT_IN_ROLES.SUPER_ADMIN]: {
    'gates:view': true,
    'gates:manage': true,
    'gates:assignments': true,
    'qr:view': true,
    'qr:create': true,
    'qr:manage': true,
    'scans:view': true,
    'scans:override': true,
    'scans:export': true,
    'workspace:manage': true,
    'roles:manage': true,
    'users:view': true,
    'users:manage': true,
    'analytics:view': true,
    'projects:view': true,
    'projects:manage': true,
    'units:view': true,
    'units:manage': true,
    'residents:manage': true,
    'contacts:manage': true,
    'maintenance:view': true,
    'maintenance:manage': true,
  },
  [BUILT_IN_ROLES.ORG_ADMIN]: {
    'gates:view': true,
    'gates:manage': true,
    'gates:assignments': true,
    'qr:view': true,
    'qr:create': true,
    'qr:manage': true,
    'scans:view': true,
    'scans:override': true,
    'scans:export': true,
    'workspace:manage': true,
    'roles:manage': true,
    'users:view': true,
    'users:manage': true,
    'analytics:view': true,
    'projects:view': true,
    'projects:manage': true,
    'units:view': true,
    'units:manage': true,
    'residents:manage': true,
    'contacts:manage': true,
    'maintenance:view': true,
    'maintenance:manage': true,
  },
  [BUILT_IN_ROLES.SECURITY_MANAGER]: {
    'gates:view': true,
    'gates:manage': true,
    'gates:assignments': true,
    'qr:view': true,
    'qr:create': false,
    'qr:manage': false,
    'scans:view': true,
    'scans:override': true,
    'scans:export': true,
    'workspace:manage': false,
    'roles:manage': false,
    'users:view': true,
    'users:manage': false,
    'analytics:view': true,
    'projects:view': true,
    'projects:manage': false,
    'units:view': false,
    'units:manage': false,
    'residents:manage': false,
    'contacts:manage': false,
    'maintenance:view': true,
    'maintenance:manage': true,
  },
  [BUILT_IN_ROLES.GATE_OPERATOR]: {
    'gates:view': true,
    'gates:manage': false,
    'gates:assignments': false,
    'qr:view': false,
    'qr:create': false,
    'qr:manage': false,
    'scans:view': true,
    'scans:override': false,
    'scans:export': false,
    'workspace:manage': false,
    'roles:manage': false,
    'users:view': false,
    'users:manage': false,
    'analytics:view': false,
    'projects:view': false,
    'projects:manage': false,
    'units:view': false,
    'units:manage': false,
    'residents:manage': false,
    'contacts:manage': false,
    'maintenance:view': true,
    'maintenance:manage': false,
  },
  [BUILT_IN_ROLES.RESIDENT]: {
    'gates:view': false,
    'gates:manage': false,
    'gates:assignments': false,
    'qr:view': true,
    'qr:create': true,
    'qr:manage': true,
    'scans:view': false,
    'scans:override': false,
    'scans:export': false,
    'workspace:manage': false,
    'roles:manage': false,
    'users:view': false,
    'users:manage': false,
    'analytics:view': false,
    'projects:view': false,
    'projects:manage': false,
    'units:view': false,
    'units:manage': false,
    'residents:manage': false,
    'contacts:manage': false,
    'maintenance:view': true,
    'maintenance:manage': true,
  },
};
